version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: cd packages/babel-plugin-vite && yarn test
      - run: cd packages/babel-plugin-vite && yarn build
      - run: cd packages/jest-environment-vite && yarn build
      - run: cd packages/vite-demo && yarn test
      - run: cd packages/vite-demo && yarn lint
